name: build

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm install
      - run: npx electron-builder --win --publish always -c.extraMetadata.version=1.0.${{ github.run_number }}
        shell: cmd
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: RentDesk-Windows-설치파일
          path: dist/*.exe
